feat(builtin): Show different times (eg. Modified, Created, Accessed) and hide categories in `ls`
lthoerner/rush pull request #51
Opened 2023-09-18 03:57 UTC by Luxzi

You can now change which timestamp is displayed in `ls` by using the following:

`-m`: Modified time
`-U`: Created time
`-u`: Accessed time

You may also hide desired categories with:

`--hide-timestamps`: Hide timestamps
`--hide-permissions`: Hide permissions
`--hide-user`: Hide file owner
`--hide-file-sizes`: Hide file sizes

2023-09-18 21:25 UTC, lthoerner requested changes
Overall it looks good, but be more careful with linting, formatting, and spelling.

2023-09-18 21:25 UTC, lthoerner commented on src/exec/builtins/functions.rs
> +enum DirectoryListTimestampMode {
This would be better as a `ValueEnum` instead of multiple `bool` flags in my opinion.

2023-09-18 21:25 UTC, lthoerner commented on src/exec/builtins/functions.rs
> +                true => DirectoryListPermissionMode::Octal,
Probably also should be a `ValueEnum` here, you can have it set to `String` by default, but this one is up to you.

2023-09-18 21:25 UTC, lthoerner commented on src/exec/builtins/functions.rs
>      let mut file_size_len_last: usize = 0;
Please be running Clippy in your editor and also setting it to autoformat with Rustfmt.

2023-09-18 21:25 UTC, lthoerner commented on src/exec/builtins/functions.rs
> +        println!("{4}{3}{2}{1}{0}",
Split this up somehow, it's too much in one block.

2023-09-18 21:25 UTC, lthoerner reviewed
Overall it looks good, but be more careful with linting, formatting, and spelling.

2023-09-19 00:32 UTC, Luxzi commented
> Overall it looks good, but be more careful with linting, formatting, and spelling.

Fix via [75718aa](https://github.com/lthoerner/rush/pull/51/commits/75718aa6463b669697c5953f9990ced9f6acefb4)

2023-09-22 22:10 UTC, lthoerner approved these changes

2023-09-22 22:51 UTC, merged